### ISSUE TITLE
Perform ontology gap analysis via curation of CTSA/gems

### ISSUE THREAD

**Issue by mellybelly** [data2health/edu-harmonization#1]
what ontologies need to be extended to serve the requirements? what are their sources? what already exists in addition to N-lighten?

**Comment by williamhersh** [comment]
I would propose that we start collecting a list of known ontologies/metadata schemas for educational resources. Here are ones I know about:

- N-Lighten - http://alaska.dev.eagle-i.net/model/
- Erudite - https://bigdatau.ini.usc.edu/explore_erudite

I know there is also Diamond, but cannot find anything about it on the Web.

Some other learning content metadata initiatives I am aware of (but do not know the current status) include:
- IEEE Learning Object Metadata - https://www.w3.org/community/lom2ld/
- Medbiquitous - https://www.medbiq.org/bring_competency_data_together

**Comment by eichmann** [comment]
DIAMOND's at https://diamondportal.org

There's no real "model" - I've had to screenscrape their data for inclusion in our index.  That said, they've some good ideas regarding classification facets (though they don't call them that)

**Comment by mellybelly** [comment]
@marijane has already done a lot of this as part of the n-lighten work, but would be good to update/re-review and see if there are any new resources.

**Comment by wondermixtape** [comment]
As per CLIC call, this will now expand to include EDU clearinghouse

**Comment by mellybelly** [comment]
@wondermixtape i think this one is done?
