### ISSUE TITLE
Create template for landscape analysis

### ISSUE THREAD

**Issue by mellybelly** [data2health/edu-harmonization#3]
This should include information about:

- [x]  the platform or source
- [x]  content types
- [x]  metadata requirements or use
- [x]  Ontology requirements or use
- [x]  Search functionality
- [x] curation functionality
- [x] ability to keep resources current
- [x] connectivity to other systems, such as institutional student systems
- [x] Attribution
- [x] licensing

**Comment by mellybelly** [comment]
@kristiholmes has some good ideas on this, please reassign as needed.

**Comment by kristiholmes** [comment]
adding @Bioscibrarian @lmkw @carsonicator @saragon02 & @pitviper6 

Pamela and Laura on the NU team contributed a similar effort for research networking systems at https://en.wikipedia.org/wiki/Comparison_of_research_networking_tools_and_research_profiling_systems which would be helpful perspective.
 
Matt’s similar assessment of repositories is here: https://github.com/data2health/repository-and-index-software (links out to collaborative spreadsheet) 
 
It would be useful to take a similar approach to examine all of the EDU platforms/efforts. 

How about if the Northwestern site takes a first run at defining the different fields/facets (and sub-facets) we want to assess (technology, data models, pathways/competencies, etc. – see Matt’s spreadsheet). We can send out to this group for comments and then reach out to the different platforrrms (N-Lighten, DIAMOND, CLIC, etc.)

**Comment by kristiholmes** [comment]
@saragon02 and @Bioscibrarian would you be able to start a Google Sheet and start organizing potential fields?  You can send it out to the rest of us and we can collaborate on it.  THANK YOU

**Comment by Bioscibrarian** [comment]
I've started the spreadsheet. You can tell I'm uncertain as to how to break up the features, so it's open for editing. When it's in a state that is more presentable, I can add it to the markdown doc, but I don't think it's ready yet. 

Link allows you to edit:
https://docs.google.com/spreadsheets/d/172IA-7TmmLNOQNMyinbAv1A0rswfAz8rE15q-yvSb-o/edit?usp=sharing

**Comment by kristiholmes** [comment]
hi! I made a couple of small edits to the table (added columns for URL and platform/technology details)

**Comment by kristiholmes** [comment]
from the CLIC site (https://clic-ctsa.org/resources/education)
which do we want to include in our assessment?  I would suggest being more inclusive than less...

**Comment by williamhersh** [comment]
Hi all, re the spreadsheet, are we cataloging ontologies or educational resources (jewels)? I thought we were collecting educational resources, but the spreadsheet looks more focused on ontologies.

Also, does anyone still use Dublin Core Metadata? I always found DCM as a nice general approach to metadata, and it seems like it could be a starting point for the metadata we want to collect on educational resources. But maybe there are newer frameworks that might work better?

**Comment by williamhersh** [comment]
> Hi all, re the spreadsheet, are we cataloging ontologies or educational resources (jewels)? I thought we were collecting educational resources, but the spreadsheet looks more focused on ontologies.
> 
> Also, does anyone still use Dublin Core Metadata? I always found DCM as a nice general approach to metadata, and it seems like it could be a starting point for the metadata we want to collect on educational resources. But maybe there are newer frameworks that might work better?

Hi everyone, I am not sure anyone saw this, so I am re-posting.

Bill
