### ISSUE TITLE
Perform mapping/alignment of ontologies

### ISSUE THREAD

**Issue by mellybelly** [data2health/edu-harmonization#4]
Mapping and alignment of Erudite meta-data/ontology (https://bioint.github.io/erudite-training-resource-standard/) to CD2H metadata working group (leveraging schema.org) to facilitate interoperability of resources. This would allow this to be mapped this to N-Lighten ontology to improve discoverability by N-Lighten (CD2H Meta-Data/Ontology curation support)

**Comment by nicolevasilevsky** [comment]
@marijane let me know if I could help with this.
