### ISSUE TITLE
perform requirements edu resource curation/discovery from CTSA websites

### ISSUE THREAD

**Issue by mellybelly** [data2health/edu-harmonization#5]
We need to understand how to best help hubs reveal their edu resources automatically using proper metadata/ontologies and schema.org @newgene @kristiholmes

**Comment by mellybelly** [comment]
As this is beyond edu alone - assignees are  @newgene and @eichmann for CD2H wide coordination

**Comment by jmcmurry** [comment]
If you haven't already, please make sure to reach out to the PIs that already expressed interest in the project. Select your project from the dropdown [here](https://docs.google.com/spreadsheets/d/1PR6jLSz3KedD9bEWQcFr-LJRQfkXo_GcFOHXZMOgd7o/edit#gid=0).

**Comment by wondermixtape** [comment]
This is actually part of cd2h-wide resource ingestion-discovery process by @eichmann

**Comment by mellybelly** [comment]
@eichmann or @wondermixtape can we close this?
