### ISSUE TITLE
Perform requirements for embedding edu search tools into CTSA hub sites

### ISSUE THREAD

**Issue by mellybelly** [data2health/edu-harmonization#6]
We want discovery mechanisms into local hub websites etc that allow search of their own as well as filterable network level resources.  This is focused on educational resources in this instance but is part of larger CD2H initiative re resource discovery (Lead CD2H wide is @eichmann - coordinated with him and rest of that team).

**Comment by wondermixtape** [comment]
@eichmann - as per CLIC call today - we need to add EDU clearinghouse to this. Call being set-up to discuss

**Comment by wondermixtape** [comment]
This is actually part of cd2h-wide resource ingestion-discovery process by @eichmann
