### ISSUE TITLE
Point of contacts for ontology work 

### ISSUE THREAD

**Issue by mellybelly** [data2health/edu-harmonization#7]
Identify point of contacts for ontology work on any identified platforms/teams so we can plan ontology work and complete preliminary mappings (e.g. Erudite, 4D, etc)

**Comment by jmcmurry** [comment]
Related: ps. This just in: a coordinated email will be going out for all projects; stay tuned.

**Comment by jmcmurry** [comment]
Baseline email was sent; all ok to proceed with project - specific communications.
